### ISSUE TITLE
Trying to search returns `NoMethodError in Catalog#index`

### ISSUE THREAD

**Issue by bibliotechy** [barmintor/dbla#37]
Followed the install instructions. Default Blacklight home page comes up, but when I search for kittens:

```
NoMethodError in Catalog#index

Showing /home/cbn/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/app/views/catalog/_index_default.html.erb where line #7 raised:

undefined method `dbla_external_link' for #<#<Class:0x007f6568146b38>:0x007f6538ce29e0>
...
```

then more stuff. 
![image](https://cloud.githubusercontent.com/assets/1128631/7405663/c0272a0a-eec3-11e4-80e0-94c8f7a77a6d.png)

Suspecting I done my ruby wrong somewhere.

**Comment by barmintor** [comment]
There's a helper include missing. I added a generator in https://github.com/barmintor/dbla/commit/1b07122a1fc431e56186f4a0e9abddc9dbfef88e , but you could also add the line:

``` ruby
module ApplicationHelper
  include Dbla::ApplicationHelperBehavior
end
```

... in app/helpers/application_helper.rb
The generator runs under rails g dbla:install, which you could run again after installing dbla v0.0.8

**Comment by bibliotechy** [comment]
Just confirming that it now now works as expected.

**Comment by barmintor** [comment]
Thanks!

**Comment by yf508** [comment]
Any progress with blacklight 6 compatibility problem? I've got the same error message on my rails app running on top of blacklight 6.4.2.
